package com.example.compose
import androidx.compose.ui.graphics.Color

// 80s Neon Theme Colors
val primaryLight = Color(0xFFFF1493) // Hot Pink
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF4A0033) // Deep Magenta
val onPrimaryContainerLight = Color(0xFFFF69B4) // Light Pink
val secondaryLight = Color(0xFF00FFFF) // Electric Cyan
val onSecondaryLight = Color(0xFF000000)
val secondaryContainerLight = Color(0xFF004D4D) // Dark Cyan
val onSecondaryContainerLight = Color(0xFF7FFFD4) // Aqua
val tertiaryLight = Color(0xFFB026FF) // Neon Purple
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF3D0066) // Deep Purple
val onTertiaryContainerLight = Color(0xFFDA70D6) // Orchid
val errorLight = Color(0xFFFF006E) // Neon Pink Error
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFF660029)
val onErrorContainerLight = Color(0xFFFF69B4)
val backgroundLight = Color(0xFF1A0033) // Deep Purple Background
val onBackgroundLight = Color(0xFFFFFFFF)
val surfaceLight = Color(0xFF2D0052) // Dark Purple Surface
val onSurfaceLight = Color(0xFFFFFFFF)
val surfaceVariantLight = Color(0xFF4A0066)
val onSurfaceVariantLight = Color(0xFFFF00FF) // Magenta
val outlineLight = Color(0xFFFF1493) // Hot Pink Outline
val outlineVariantLight = Color(0xFF9D00FF)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFFFFFFFF)
val inverseOnSurfaceLight = Color(0xFF1A0033)
val inversePrimaryLight = Color(0xFF00FFFF)
val surfaceDimLight = Color(0xFF1A0033)
val surfaceBrightLight = Color(0xFF5500AA)
val surfaceContainerLowestLight = Color(0xFF0A0A0A)
val surfaceContainerLowLight = Color(0xFF1A0033)
val surfaceContainerLight = Color(0xFF2D0052)
val surfaceContainerHighLight = Color(0xFF3D0066)
val surfaceContainerHighestLight = Color(0xFF5500AA)

val primaryLightMediumContrast = Color(0xFF000000)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF1B1B1B)
val onPrimaryContainerLightMediumContrast = Color(0xFFA7A7A7)
val secondaryLightMediumContrast = Color(0xFF363636)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF6D6D6D)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF000000)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF1B1B1B)
val onTertiaryContainerLightMediumContrast = Color(0xFFA7A7A7)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF9F9F9)
val onBackgroundLightMediumContrast = Color(0xFF1B1B1B)
val surfaceLightMediumContrast = Color(0xFFF9F9F9)
val onSurfaceLightMediumContrast = Color(0xFF111111)
val surfaceVariantLightMediumContrast = Color(0xFFEBE0E1)
val onSurfaceVariantLightMediumContrast = Color(0xFF3B3436)
val outlineLightMediumContrast = Color(0xFF585152)
val outlineVariantLightMediumContrast = Color(0xFF736B6C)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF303030)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF1F1F1)
val inversePrimaryLightMediumContrast = Color(0xFFC6C6C6)
val surfaceDimLightMediumContrast = Color(0xFFC6C6C6)
val surfaceBrightLightMediumContrast = Color(0xFFF9F9F9)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF3F3F3)
val surfaceContainerLightMediumContrast = Color(0xFFE8E8E8)
val surfaceContainerHighLightMediumContrast = Color(0xFFDDDDDD)
val surfaceContainerHighestLightMediumContrast = Color(0xFFD1D1D1)

val primaryLightHighContrast = Color(0xFF000000)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF1B1B1B)
val onPrimaryContainerLightHighContrast = Color(0xFFD0D0D0)
val secondaryLightHighContrast = Color(0xFF2C2C2C)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF494949)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF000000)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF1B1B1B)
val onTertiaryContainerLightHighContrast = Color(0xFFD0D0D0)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF9F9F9)
val onBackgroundLightHighContrast = Color(0xFF1B1B1B)
val surfaceLightHighContrast = Color(0xFFF9F9F9)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFEBE0E1)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF312B2C)
val outlineVariantLightHighContrast = Color(0xFF4F4749)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF303030)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFC6C6C6)
val surfaceDimLightHighContrast = Color(0xFFB9B9B9)
val surfaceBrightLightHighContrast = Color(0xFFF9F9F9)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF1F1F1)
val surfaceContainerLightHighContrast = Color(0xFFE2E2E2)
val surfaceContainerHighLightHighContrast = Color(0xFFD4D4D4)
val surfaceContainerHighestLightHighContrast = Color(0xFFC6C6C6)

// 80s Neon Dark Theme (Primary theme for neon aesthetic)
val primaryDark = Color(0xFFFF1493) // Hot Pink
val onPrimaryDark = Color(0xFF000000)
val primaryContainerDark = Color(0xFF660033) // Deep Magenta
val onPrimaryContainerDark = Color(0xFFFF69B4) // Light Pink
val secondaryDark = Color(0xFF00FFFF) // Electric Cyan
val onSecondaryDark = Color(0xFF000000)
val secondaryContainerDark = Color(0xFF006666) // Teal
val onSecondaryContainerDark = Color(0xFF7FFFD4) // Aqua
val tertiaryDark = Color(0xFFB026FF) // Neon Purple
val onTertiaryDark = Color(0xFF000000)
val tertiaryContainerDark = Color(0xFF5500AA) // Purple
val onTertiaryContainerDark = Color(0xFFDA70D6) // Orchid
val errorDark = Color(0xFFFF006E) // Neon Pink
val onErrorDark = Color(0xFF000000)
val errorContainerDark = Color(0xFF8B0040) // Dark Pink
val onErrorContainerDark = Color(0xFFFF69B4)
val backgroundDark = Color(0xFF0A0A0A) // Almost Black
val onBackgroundDark = Color(0xFFFFFFFF)
val surfaceDark = Color(0xFF1A0033) // Deep Purple
val onSurfaceDark = Color(0xFFFFFFFF)
val surfaceVariantDark = Color(0xFF2D0052) // Dark Purple
val onSurfaceVariantDark = Color(0xFF00FFFF) // Cyan
val outlineDark = Color(0xFFFF00FF) // Magenta
val outlineVariantDark = Color(0xFF9D00FF) // Purple
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFFFFFFF)
val inverseOnSurfaceDark = Color(0xFF0A0A0A)
val inversePrimaryDark = Color(0xFF00FFFF) // Cyan
val surfaceDimDark = Color(0xFF0A0A0A)
val surfaceBrightDark = Color(0xFF3D0066) // Bright Purple
val surfaceContainerLowestDark = Color(0xFF000000)
val surfaceContainerLowDark = Color(0xFF1A0033)
val surfaceContainerDark = Color(0xFF2D0052)
val surfaceContainerHighDark = Color(0xFF3D0066)
val surfaceContainerHighestDark = Color(0xFF5500AA)

val primaryDarkMediumContrast = Color(0xFFDCDCDC)
val onPrimaryDarkMediumContrast = Color(0xFF262626)
val primaryContainerDarkMediumContrast = Color(0xFF919191)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFDCDCDC)
val onSecondaryDarkMediumContrast = Color(0xFF262626)
val secondaryContainerDarkMediumContrast = Color(0xFF919191)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFDCDCDC)
val onTertiaryDarkMediumContrast = Color(0xFF262626)
val tertiaryContainerDarkMediumContrast = Color(0xFF919191)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF131313)
val onBackgroundDarkMediumContrast = Color(0xFFE2E2E2)
val surfaceDarkMediumContrast = Color(0xFF131313)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF4C4546)
val onSurfaceVariantDarkMediumContrast = Color(0xFFE5DADB)
val outlineDarkMediumContrast = Color(0xFFBAAFB1)
val outlineVariantDarkMediumContrast = Color(0xFF988E8F)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE2E2E2)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF2A2A2A)
val inversePrimaryDarkMediumContrast = Color(0xFF484848)
val surfaceDimDarkMediumContrast = Color(0xFF131313)
val surfaceBrightDarkMediumContrast = Color(0xFF444444)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF070707)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1D1D1D)
val surfaceContainerDarkMediumContrast = Color(0xFF282828)
val surfaceContainerHighDarkMediumContrast = Color(0xFF323232)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3E3E3E)

val primaryDarkHighContrast = Color(0xFFF0F0F0)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFC2C2C2)
val onPrimaryContainerDarkHighContrast = Color(0xFF0B0B0B)
val secondaryDarkHighContrast = Color(0xFFF0F0F0)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFC2C2C2)
val onSecondaryContainerDarkHighContrast = Color(0xFF0B0B0B)
val tertiaryDarkHighContrast = Color(0xFFF0F0F0)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFC2C2C2)
val onTertiaryContainerDarkHighContrast = Color(0xFF0B0B0B)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF131313)
val onBackgroundDarkHighContrast = Color(0xFFE2E2E2)
val surfaceDarkHighContrast = Color(0xFF131313)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF4C4546)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFF9EDEF)
val outlineVariantDarkHighContrast = Color(0xFFCBC0C1)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE2E2E2)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF484848)
val surfaceDimDarkHighContrast = Color(0xFF131313)
val surfaceBrightDarkHighContrast = Color(0xFF505050)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1F1F1F)
val surfaceContainerDarkHighContrast = Color(0xFF303030)
val surfaceContainerHighDarkHighContrast = Color(0xFF3B3B3B)
val surfaceContainerHighestDarkHighContrast = Color(0xFF474747)







